version: '3.8'

services:
  api:
    build: .
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    volumes:
      - .db_data:/usr/src/app/data
    restart: always

volumes:
  .db_data:
